[package]
name = "rusty_ollama"
version = "0.0.1"
description = "A Ollama client written in Rust"
authors = ["Dax911", "sammcj", "simoncollins"]
license = "MIT"
repository = "https://github.com/ai-qol-things/rusty-ollama/"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.11.22"
tokio = "1.33.0"
thiserror = "1.0.50"

[target."cfg(target_os = \"macos\")".dependencies]
core-graphics = {version = "0.23"}
core-foundation = { version = "0.9.3" }
cocoa = { version = "0.25" }
objc =  { version = "0.2.7" }
objc_id = {version = "0.1.1" }
objc-foundation = { version = "0.1.1" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
default = ["custom-protocol"]
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
